name: Build PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Build firmware
      run: pio run --environment lilygo-t5-v213
      
    - name: Build filesystem image
      run: pio run --target buildfs --environment lilygo-t5-v213
      
    - name: Verify build outputs
      run: |
        echo "✅ Build completed successfully!"
        echo "📦 Firmware binary: $(ls -lh .pio/build/lilygo-t5-v213/firmware.bin)"
        echo "📦 Filesystem image: $(ls -lh .pio/build/lilygo-t5-v213/spiffs.bin)" 